In [1]:
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup
from tqdm import tqdm

In [2]:
def scrapweb(url):
    driver = webdriver.Chrome()
    driver.get(url)
#     driver.implicitly_wait(5)
    soup = BeautifulSoup(driver.page_source,'lxml')
    tables = soup.find_all('table')
    dfs = pd.read_html(str(tables))[0]
    input_tag = driver.find_element_by_id('big_table_next')
    nextButtonClass =(input_tag.get_attribute('class'))
    while("paginate_button_disabled" not in nextButtonClass):
        driver.find_element_by_id('big_table_next').click()
        soup = BeautifulSoup(driver.page_source,'lxml')
        tables = soup.find_all('table')
        df = pd.read_html(str(tables))
        dfs =dfs.append(df[0])
        nextButtonClass=driver.find_element_by_id('big_table_next').get_attribute('class')
    driver.close()
    return dfs

In [3]:
dfs = scrapweb('https://www.bankeauctions.com/')
print(dfs)

    Unnamed: 0  Auction ID                             Bank Name  \
0          NaN      118404                Repco Home Finance Ltd
1          NaN      118371                  Punjab National Bank
2          NaN      118939  CITIZENCREDIT Co-Operative Bank Ltd.
3          NaN      118941  CITIZENCREDIT Co-Operative Bank Ltd.
4          NaN      118943  CITIZENCREDIT Co-Operative Bank Ltd.
..         ...         ...                                   ...
5          NaN      118269   Omkara Asset Reconstruction Pvt Ltd
6          NaN      118270   Omkara Asset Reconstruction Pvt Ltd
7          NaN      118271   Omkara Asset Reconstruction Pvt Ltd
8          NaN      118272   Omkara Asset Reconstruction Pvt Ltd
9          NaN      119073                 Central Bank Of India

                                     Asset on Auction         City  \
0   Description of Property: All that Piece and pa...  Thiruvallur
1   Lot No. (Immoveable Properties along with Buil...     Hamirpur
2   Property No.1 Shop No 1, Ground Floor, Rupji M...       Mumbai
3   Property No.2 Unit Nos. L-1,2,3, 1st Floor, Te...       Mumbai
4   Property No.3 Flat No.101, 1st Floor admeasuri...  Navi Mumbai
..                                                ...          ...
5   All that part and parcel of the immovable prop...       Mumbai
6   All that part and parcel of the property beari...         Pune
7   All that part and parcel of the property Flat ...         Pune
8   All that part and parcel of the property Flat ...         Pune
9   Registered Owner: Shri Aditya Roy vide deed No...        Nadia

   Sealed Bid Submission last date  Reserve Price        EMD Event Type  \
0                      23 Sep 2021      9113000.0   911300.0   SARFAESI
1                      23 Sep 2021     10422000.0  1042200.0        DRT
2                      23 Sep 2021     34690000.0  3469000.0   SARFAESI
3                      23 Sep 2021     45423000.0  4542300.0   SARFAESI
4                      23 Sep 2021      2365200.0   236520.0   SARFAESI
..                             ...            ...        ...        ...
5                      23 Sep 2021     16500000.0  1650000.0   SARFAESI
6                      23 Sep 2021      2520000.0   252000.0   SARFAESI
7                      23 Sep 2021      2470000.0   247000.0   SARFAESI
8                      23 Sep 2021      1780000.0   178000.0   SARFAESI
9                      24 Sep 2021       568000.0    60000.0   SARFAESI

            DRT Name
0                 --
1   Chandigarh DRT-I
2                 --
3                 --
4                 --
..               ...
5                 --
6                 --
7                 --
8                 --
9                 --

[1050 rows x 10 columns]

In [4]:
dfs.columns

Index(['Unnamed: 0', 'Auction ID', 'Bank Name', 'Asset on Auction', 'City',
       'Sealed Bid Submission last date', 'Reserve Price', 'EMD', 'Event Type',
       'DRT Name'],
      dtype='object')

In [5]:
dfs.head()

,Unnamed: 0,Auction ID,Bank Name,Asset on Auction,City,Sealed Bid Submission last date,Reserve Price,EMD,Event Type,DRT Name
0,NaN,118404,Repco Home Finance Ltd,Description of Property: All that Piece and pa...,Thiruvallur,23 Sep 2021,9113000.0,911300.0,SARFAESI,--
1,NaN,118371,Punjab National Bank,Lot No. (Immoveable Properties along with Buil...,Hamirpur,23 Sep 2021,10422000.0,1042200.0,DRT,Chandigarh DRT-I
2,NaN,118939,CITIZENCREDIT Co-Operative Bank Ltd.,"Property No.1 Shop No 1, Ground Floor, Rupji M...",Mumbai,23 Sep 2021,34690000.0,3469000.0,SARFAESI,--
3,NaN,118941,CITIZENCREDIT Co-Operative Bank Ltd.,"Property No.2 Unit Nos. L-1,2,3, 1st Floor, Te...",Mumbai,23 Sep 2021,45423000.0,4542300.0,SARFAESI,--
4,NaN,118943,CITIZENCREDIT Co-Operative Bank Ltd.,"Property No.3 Flat No.101, 1st Floor admeasuri...",Navi Mumbai,23 Sep 2021,2365200.0,236520.0,SARFAESI,--

In [6]:
dfs.to_pickle("Bankeauctions_data.pkl")